name: Monthly catalog update

on:
  schedule:
    - cron: "10 8 1 * *"   # Runs on the 1st of every month at 08:10 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
