name: Monthly catalog update

on:
  schedule:
    - cron: "10 8 1 * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run update script
        env:
          MINERSTAT_API_KEY: ${{ secrets.MINERSTAT_API_KEY }}
        run: node scripts/update-catalogs.mjs

      - name: Commit & push data changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "catalog-bot"
          git config user.email "catalog-bot@users.noreply.github.com"

          git add data/
          git diff --cached --quiet || git commit -m "Monthly catalog update"

          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push origin main
