name: Monthly catalog update v2

on:
  schedule:
    - cron: "10 8 1 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run update script
        env:
          MINERSTAT_API_KEY: ${{ secrets.MINERSTAT_API_KEY }}
        run: node scripts/update-catalogs.mjs

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -e

          git config --global user.name "catalog-bot"
          git config --global user.email "catalog-bot@users.noreply.github.com"

          git add data/

          if git diff --cached --quiet; then
            echo "No ch
